    -- horse training
    ['horsetrainingbrush']  = {['name'] = 'horsetrainingbrush',  ['label'] = 'Trainer Brush',  ['weight'] = 300, ['type'] = 'item', ['image'] = 'horsebrush.png', ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'brush used by a horse trainer'},
    ['horsetrainingcarrot'] = {['name'] = 'horsetrainingcarrot', ['label'] = 'Trainer Carrot', ['weight'] = 100, ['type'] = 'item', ['image'] = 'carrot.png',     ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'carrot used by a horse trainer'},

    -- horse xp tokens
    ['horsexp5']   = {['name'] = 'horsexp5',   ['label'] = '5 Horse XP',   ['weight'] = 0,    ['type'] = 'item', ['image'] = 'horsexp.png', ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used to add xp to for horses'},
    ['horsexp10']  = {['name'] = 'horsexp10',  ['label'] = '10 Horse XP',  ['weight'] = 0,    ['type'] = 'item', ['image'] = 'horsexp.png', ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used to add xp to for horses'},
    ['horsexp25']  = {['name'] = 'horsexp25',  ['label'] = '25 Horse XP',  ['weight'] = 0,    ['type'] = 'item', ['image'] = 'horsexp.png', ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used to add xp to for horses'},
    ['horsexp50']  = {['name'] = 'horsexp50',  ['label'] = '50 Horse XP',  ['weight'] = 0,    ['type'] = 'item', ['image'] = 'horsexp.png', ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used to add xp to for horses'},
    ['horsexp100'] = {['name'] = 'horsexp100', ['label'] = '100 Horse XP', ['weight'] = 0,    ['type'] = 'item', ['image'] = 'horsexp.png', ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'used to add xp to for horses'},
